# 01. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import os

# 02. Importing Data

In [2]:
# Importing data from last assignment

In [3]:
path_ords_prods_merge = r'/Users/robertochidiac/Desktop/Instacart Basket Analysis/Data/Prepared Data/orders_products_merged_derived.pkl'

In [4]:
path_ords_prods_merge

'/Users/robertochidiac/Desktop/Instacart Basket Analysis/Data/Prepared Data/orders_products_merged_derived.pkl'

In [5]:
df_ords_prods_merge = pd.read_pickle(os.path.join(path_ords_prods_merge))

In [7]:
df_ords_prods_merge.head().drop(['Unnamed: 0_x', 'Unnamed: 0.1', 'Unnamed: 0_y'], axis = 1)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,ordered_today,product_id,add_to_cart_order,...,product_name,aisle_id,department_id,prices,exists,price_range_loc,busiest_day,busiest_days,slowest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,True,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders
1,2398795,1,prior,2,3,7,15.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Average orders
2,473747,1,prior,3,3,12,21.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders
3,2254736,1,prior,4,4,7,29.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Average orders
4,431534,1,prior,5,4,15,28.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders

In [ ]:
# The code below will create a subset of the dataframe above

In [8]:
df_subset_merge = df_ords_prods_merge[:1000000]

In [9]:
df_subset_merge.shape

(1000000, 25)

In [12]:
df_subset_merge.head(10).drop(['Unnamed: 0_x', 'Unnamed: 0.1', 'Unnamed: 0_y'], axis = 1)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,ordered_today,product_id,add_to_cart_order,...,product_name,aisle_id,department_id,prices,exists,price_range_loc,busiest_day,busiest_days,slowest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,True,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders
1,2398795,1,prior,2,3,7,15.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Average orders
2,473747,1,prior,3,3,12,21.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders
3,2254736,1,prior,4,4,7,29.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Average orders
4,431534,1,prior,5,4,15,28.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders
5,3367565,1,prior,6,2,7,19.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Average orders
6,550135,1,prior,7,1,9,20.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders
7,3108588,1,prior,8,1,14,14.0,False,196,2,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders
8,2295261,1,prior,9,1,16,0.0,False,196,4,...,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders
9,2550362,1,prior,10,4,8,30.0,False,196,1,...,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders

In [ ]:
# The code below will use the groupby() function to group our dataframe by a given column

In [13]:
df_subset_merge.groupby('product_name')

In [ ]:
# the code below will group and aggregate data by combining the groupby() and agg() function

In [14]:
df_subset_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [15]:
# The code below will give the same result as the code above, but without the use of the agg() function
df_subset_merge.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [16]:
# The code below will perform a multiple aggregation
df_subset_merge.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

In [18]:
# The code below will help us create a new column with the transform() function
df_subset_merge['max_order'] = df_subset_merge.groupby(['user_id'])['order_number'].transform(np.max)

/Users/robertochidiac/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [20]:
df_subset_merge.head(15).drop(['Unnamed: 0_x', 'Unnamed: 0.1', 'Unnamed: 0_y'], axis = 1)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,ordered_today,product_id,add_to_cart_order,...,aisle_id,department_id,prices,exists,price_range_loc,busiest_day,busiest_days,slowest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,True,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,10
1,2398795,1,prior,2,3,7,15.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Average orders,10
2,473747,1,prior,3,3,12,21.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,10
3,2254736,1,prior,4,4,7,29.0,False,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Average orders,10
4,431534,1,prior,5,4,15,28.0,False,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,10
5,3367565,1,prior,6,2,7,19.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Average orders,10
6,550135,1,prior,7,1,9,20.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,10
7,3108588,1,prior,8,1,14,14.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,10
8,2295261,1,prior,9,1,16,0.0,False,196,4,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,10
9,2550362,1,prior,10,4,8,30.0,False,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,10
10,2968173,15,prior,15,1,9,7.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,22
11,1870022,15,prior,17,2,16,8.0,False,196,6,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,22
12,1911383,15,prior,18,2,11,7.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,22
13,2715276,15,prior,21,1,9,7.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,22
14,487368,15,prior,22,1,10,14.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,22

In [21]:
df_subset_merge.head(100).drop(['Unnamed: 0_x', 'Unnamed: 0.1', 'Unnamed: 0_y'], axis = 1)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,ordered_today,product_id,add_to_cart_order,...,aisle_id,department_id,prices,exists,price_range_loc,busiest_day,busiest_days,slowest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,True,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,10
1,2398795,1,prior,2,3,7,15.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Average orders,10
2,473747,1,prior,3,3,12,21.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,10
3,2254736,1,prior,4,4,7,29.0,False,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Average orders,10
4,431534,1,prior,5,4,15,28.0,False,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,10
5,3367565,1,prior,6,2,7,19.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Average orders,10
6,550135,1,prior,7,1,9,20.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,10
7,3108588,1,prior,8,1,14,14.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,10
8,2295261,1,prior,9,1,16,0.0,False,196,4,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,10
9,2550362,1,prior,10,4,8,30.0,False,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,10
10,2968173,15,prior,15,1,9,7.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,22
11,1870022,15,prior,17,2,16,8.0,False,196,6,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,22
12,1911383,15,prior,18,2,11,7.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,22
13,2715276,15,prior,21,1,9,7.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,22
14,487368,15,prior,22,1,10,14.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,22
15,2293453,19,prior,2,5,14,6.0,False,196,3,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,7
16,1973799,19,prior,5,6,12,8.0,False,196,15,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,7
17,532817,19,prior,7,4,17,6.0,False,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,7
18,1573906,21,prior,10,3,10,6.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,33
19,1593000,31,prior,10,3,8,7.0,False,196,17,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,17
20,2231262,31,prior,17,3,11,8.0,False,196,14,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,17
21,2580647,43,prior,6,4,16,4.0,False,196,9,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,9
22,2187180,43,prior,9,4,12,3.0,False,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,9
23,2497897,52,prior,1,1,9,NaN,True,196,4,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,27
24,1318871,52,prior,2,1,10,7.0,False,196,5,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,27
25,1261384,52,prior,3,1,10,7.0,False,196,3,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,27
26,580568,52,prior,5,2,10,8.0,False,196,6,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,27
27,2428073,52,prior,7,2,7,8.0,False,196,5,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Average orders,27
28,342306,52,prior,9,1,11,7.0,False,196,5,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,27
29,1520353,52,prior,10,2,10,8.0,False,196,4,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,2846344,98,prior,11,4,13,15.0,False,196,2,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,14
71,747431,98,prior,12,6,13,30.0,False,196,4,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,14
72,2383054,98,prior,13,4,11,30.0,False,196,1,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,14
73,1993729,98,prior,14,5,8,8.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,14
74,1403849,109,prior,3,3,17,9.0,False,196,5,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,3
75,520620,120,prior,1,3,11,NaN,True,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,3
76,3273029,120,prior,3,2,8,19.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,3
77,1861943,185,prior,2,1,12,25.0,False,196,10,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,2
78,2040988,195,prior,1,1,14,NaN,True,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,57
79,1680569,195,prior,8,1,9,4.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,57
80,276171,195,prior,19,5,11,3.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,57
81,2744976,195,prior,22,5,10,7.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,57
82,2781919,195,prior,25,1,14,4.0,False,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,57
83,1738718,195,prior,31,2,8,4.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,57
84,3058369,195,prior,34,3,10,6.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,57
85,1485596,195,prior,37,2,15,0.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,57
86,417035,195,prior,40,3,16,2.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,57
87,1615297,195,prior,47,5,10,2.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,57
88,1765587,195,prior,52,3,12,2.0,False,196,3,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,57
89,745908,195,prior,57,4,11,3.0,False,196,3,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,57
90,2505656,222,prior,17,2,12,1.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,38
91,3268370,222,prior,38,5,15,1.0,False,196,6,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,38
92,2016711,290,prior,9,5,19,6.0,False,196,8,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,45
93,2706088,290,prior,28,6,10,7.0,False,196,16,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,45
94,1952286,331,prior,6,5,16,30.0,False,196,8,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,6
95,3226575,360,prior,1,5,12,NaN,True,196,1,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,1
96,1469869,377,prior,3,5,17,3.0,False,196,9,...,77,7,9.0,both,Mid-range product,Regularly busy,Regular days,Regular days,Most orders,3
97,1927023,387,prior,2,4,10,22.0,False,196,3,...,77,7,9.0,both,Mid-range product,Least busy,Slowest days,Slowest days,Most orders,2
98,858092,420,prior,4,1,19,30.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Busiest days,Busiest days,Most orders,5
99,119314,420,prior,5,3,19,16.0,False,196,2,...,77,7,9.0,both,Mid-range product,Regularly busy,Slowest days,Slowest days,Most orders,5

In [ ]:
# The codes below will create a flag from the newly created column 'max_order'

In [23]:
df_subset_merge.loc[df_subset_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [24]:
df_subset_merge.loc[(df_subset_merge['max_order'] <= 40) & (df_subset_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [25]:
df_subset_merge.loc[df_subset_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [26]:
df_subset_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    463844
Loyal customer      335086
New customer        201070
Name: loyalty_flag, dtype: int64

In [27]:
# The code below will help use check our flagged column by selecting only column we want to see
df_subset_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             2
2         1      New customer             3
3         1      New customer             4
4         1      New customer             5
5         1      New customer             6
6         1      New customer             7
7         1      New customer             8
8         1      New customer             9
9         1      New customer            10
10       15  Regular customer            15
11       15  Regular customer            17
12       15  Regular customer            18
13       15  Regular customer            21
14       15  Regular customer            22
15       19      New customer             2
16       19      New customer             5
17       19      New customer             7
18       21  Regular customer            10
19       31  Regular customer            10
20       31  Regular customer            17
21       43      New customer             6
22       43      New customer             9
23       52  Regular customer             1
24       52  Regular customer             2
25       52  Regular customer             3
26       52  Regular customer             5
27       52  Regular customer             7
28       52  Regular customer             9
29       52  Regular customer            10
30       52  Regular customer            11
31       52  Regular customer            12
32       52  Regular customer            15
33       52  Regular customer            17
34       52  Regular customer            18
35       52  Regular customer            19
36       52  Regular customer            21
37       67  Regular customer             1
38       67  Regular customer             2
39       67  Regular customer             3
40       67  Regular customer             4
41       67  Regular customer             5
42       67  Regular customer             6
43       67  Regular customer             8
44       67  Regular customer             9
45       67  Regular customer            10
46       67  Regular customer            11
47       67  Regular customer            12
48       67  Regular customer            13
49       67  Regular customer            14
50       67  Regular customer            16
51       67  Regular customer            18
52       67  Regular customer            19
53       67  Regular customer            21
54       67  Regular customer            22
55       67  Regular customer            23
56       81      New customer             3
57       81      New customer             5
58       82  Regular customer             1
59       82  Regular customer             3